<?php

namespace AppBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryAllByAlbum($albumId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT i.id, i.filename, i.description FROM AppBundle:Image i
                 WHERE i.album = :albumId
                 ORDER BY i.filename ASC'
            )
            ->setParameter('albumId', $albumId)
        ;
    }
}
