app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /

app_rest:
    resource: "@AppBundle/Resources/config/routing-rest.yml"
    type: rest
    options:
        expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"