services:
    app.album_fixture_importer:
        class: AppBundle\FixtureImporter\AlbumFixtureImporter
        arguments:
            - @doctrine.orm.entity_manager
            - "%stof_doctrine_extensions.default_file_path%/images"
            - "%app.fixtures_path%/images"